import = ["/home/chris/.config/alacritty/themes/rose-pine.toml"]

[colors.primary]
background = "#000000"

[cursor]
blink_interval = 500
thickness = 0.25

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_title = true
opacity = 0.75
startup_mode = "Maximized"

[window.dimensions]
columns = 140
lines = 40
