# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

command_timeout=1000

[line_break]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold red)"

[status]
style = "bg:red"
symbol = ""
format = '[\[$symbol$status\]]($style) '
disabled = false

[package]
disabled = true

[username]
style_user = "bright-purple bold"
style_root = "bright-red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = true
format = '@[$hostname](bold bright-yellow)'
disabled = false

[directory]
style = 'bold cyan'
read_only_style = 'red'
truncate_to_repo = false
truncation_length = 5 
truncation_symbol = ''
read_only = '🔒'
format = ' [$path]($style)[$read_only]($read_only_style) '
home_symbol = '~'

[lua]
disabled = true
format = '[$symbol]($style)'

[docker_context]
format = "via [🐋 $context](blue bold)"

[cmd_duration]
disabled = true

[cobol]
disabled = true

[time]
disabled = true

[cmake]
disabled = true

[c]
disabled = true
format = '[$symbol]($style)'

[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = false

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true
format = '[$symbol]($style)'

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[kotlin]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true
format = '[$symbol]($style)'

[php]
disabled = true
format = '[$symbol]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
format = '[$symbol]($style)'

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[zig]
disabled = true
format = '[$symbol]($style)'

[purescript]
disabled = true
