# [colors.primary]
# background = "#000000"

[cursor]
blink_interval = 500
thickness = 0.25

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 9.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_title = true
# opacity = 0.75
opacity = 1
startup_mode = "Maximized"

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 3
y = 0

[general]
import = ["/home/chris/.config/alacritty/themes/gruvbox_dark.toml"]

[terminal]
