# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

#####################################################################

alias v='exa -l'
alias vr='exa -lRL'
alias vv='exa -la'
alias vvr='exa -laRL'
alias grep='grep --color=auto'
alias n='netstat -naepout'
alias ip='ip --color'
alias ipa='ip --color -4 a'
alias df='df -Th'
alias st='colortail -n40 -f /var/log/syslog'
alias mc='. /usr/share/mc/bin/mc-wrapper.sh'
alias vg='valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all -v'
alias vgl='valgrind --leak-check=full --track-origins=yes -v --log-file=valgrind.log'
alias running_services='systemctl list-units --type=service'
alias gpg-FORGET-card='gpgconf --kill gpg-agent'
alias gpg-SWITCH-card='gpg-connect-agent "scd serialno" "learn --force" /bye'
alias gpg-WAKE-card='systemctl restart pcscd'
alias installed_packages_info="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
alias packages_info="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse"

export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Prevent auto complete of non-executable files in path
setopt hashexecutablesonly
setopt rm_star_silent
setopt extendedglob
setopt no_share_history

export PATH=$PATH:/usr/local/go/bin:/opt/cuda/bin
